### ISSUE TITLE
BUG `elcord-wsl--load-path` wsl-path and windows-path

### ISSUE THREAD

**Issue by Bihart** [cheeze2000/elcord-wsl#1]
I had a problem whit `node.exe`, as it was not always communcating whit
`index.js` in the wsl directory (I found this out from the pm2 logs), I guess
the communication between wsl and windows failed, so i used `wslpath -w` to fix
it, I don't know if it was a proble that only happened to me, but still I open
the topic and add my solution in case it's useful for someone.

In the `elcord-wsl--connet` function change this

```lisp
(shell-command
  (concat "pm2 start \"\\\""
     elcord-wsl--node-path
     "\\\" " elcord-wsl--load-path "/index.js\" "
     "--name elcord-wsl"))))))
```

to

```lisp
(let ((path-parse
       (concat
          "$(wslpath -w  " elcord-wsl--load-path "/index.js | sed 's/\\\\/\\\\\\\\/g')" ))
    (head-command
       (concat
          '"pm2 start \"'" elcord-wsl--node-path "'")))
   (shell-command
      (concat head-command " " path-parse "\" --name elcord-wsl")))))))
```
I don't know if this is the best solution, but I am open to suggestions.

**Comment by cheeze2000** [comment]
thank you for raising this issue. unfortunately, i have stopped using emacs and have since decided to stop maintaining this repository. feel free to modify it to your liking
